### ISSUE TITLE
'parent_submission' > 'author' not being parsed correctly?

### ISSUE THREAD

**Issue by magn2o** [josephwegner/better-auto-moderator#2]
Using the following rule:

```
type: comment
body (full-text): "!foo"
author:
    is_moderator: true
parent_submission:
    author:
        set_flair: "foobar"
        overwrite_flair: true
```

BAM applies the flair "foobar" to the _comment_ author, rather than the author of the _parent_submission_.

However, if I drop the nested 'author' sub-group:

```
type: comment
body (full-text): "!foo"
author:
    is_moderator: true
parent_submission:
    set_flair: "foobar"
    overwrite_flair: true
```

The log indicates that it is flairing the submission author, but no flair is actually applied.
